spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:news_service_db}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}
