spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:userprofile_service_db}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    fetchRegistry: true
    registerWithEureka: true
